## Esame Metodi Numerici  4 Luglio 2024 - Turno I Ore 9

# Esercizio 1

Si consideri il sistema lineare:

     A  x = b 

dove A è la matrice dei coefficienti, b è il termine noto, ed x è il vettore delle incognite da determinare.
I dati di questo sistema lineare sono contenuti nel file **testI.mat**.

- Si implementino e si testino sui dati forniti due metodi che sono adatti a risolvere tale sistema lineare con le caratteristiche delle matrici dei coefficienti date in input.
                                      **[punti 7]**
- Si confrontino i risultati ottenuti e si giustifichino utilizzando  e richiamando gli aspetti teorici dei metodi implementati.
                                      **[punti 2]**

Per la lettura dei dati procedere nel seguente modo:

``from scipy.io import loadmat``

``import numpy as np``

``dati = loadmat('testI')``

``A=dati["A"] ``

``A=A.astype(float)``

`` b=dati["b"] ``

`` b=b.astype(float)``

In [98]:
from scipy.io import loadmat
import scipy as sp
import numpy as np
dati = loadmat('test_4_luglioI')
A=dati["A"] 
A=A.astype(float)
b=dati["b"]
b=b.astype(float)

In [100]:
elemA = np.count_nonzero(A)
sizeA = A.size

print("A è densa?", elemA / sizeA > 0.33)

A è densa? False


In [101]:
def jacobi(A,b,x0,toll,it_max):
    errore=1000
    d=np.diag(A)
    n=A.shape[0]
    invM=np.diag(1/d)
    E=np.tril(A, -1)
    F=np.triu(A, 1)
    N=-(E + F)
    T=invM@N
    autovalori=np.linalg.eigvals(T)
    raggiospettrale=np.max(np.abs(autovalori))
    print("raggio spettrale jacobi", raggiospettrale)
    it=0
    
    er_vet=[]
    while it<=it_max and errore>=toll:
        x= (N@x0 + b) / d.reshape(n, 1)
        errore=np.linalg.norm(x - x0) / np.linalg.norm(x) 
        er_vet.append(errore)
        x0=x.copy()
        it=it+1
    return x,it,er_vet

In [104]:
def gauss_seidel(A,b,x0,toll,it_max):
    errore=1000
    d=np.diag(A)
    D=np.diag(d)
    E=np.tril(A, -1)
    F=np.triu(A, 1)
    M=D + E
    N=-F
    T=np.linalg.inv(M)@N
    autovalori=np.linalg.eigvals(T)
    raggiospettrale=np.max(np.abs(autovalori))
    print("raggio spettrale Gauss-Seidel ",raggiospettrale)
    it=0
    er_vet=[]
    while it<=it_max and errore>=toll:
        x=np.linalg.solve(M, N@x0 + b)
        errore=np.linalg.norm(x - x0) / np.linalg.norm(x) 
        er_vet.append(errore)
        x0=x.copy()
        it=it+1
    return x,it,er_vet

In [105]:
tol = 1e-12
maxit = 200

x0 = np.zeros_like(b)

xj, itj, erj = jacobi(A, b, x0, tol, maxit)
xgs, itgs, ergs = gauss_seidel(A, b, x0, tol, maxit)

print("Iterazioni jacobi:", itj)
print("Iterazioni gauss seidel:", itgs)

raggio spettrale jacobi 0.48209261553629823
raggio spettrale Gauss-Seidel  0.28897377801649166
Iterazioni jacobi: 38
Iterazioni gauss seidel: 23


Il fattore di convergenza del problema dei metodi per la risoluzione di sistemi lineari iterativi è il raggio spettrale della matrice di iterazione T = (M^-1)*N. Dato che il raggio spettrale di jacobi è maggiore di quello di gauss seidel, gauss seidel convergerà più velocemente.

- Data la matrice
$$
\left[
\begin{array}{cccc}
3.0 & 2.0 & 1.0 & -1.0\\
4.0 & 6.0 & 3.0 & 2.0\\
2.0 & 1.0 & 4.0 & 3.0\\
1.0 & 4.0 & 2.0 & 7.0
\end{array}
\right ],
$$
calcolarne la fattorizzazione lu di Gauss  facendo uso della funzione scipy.linalg.lu e:
- sfruttarla per il calcolo del suo determinante (confrontare l'esattezza del calcolo con quello ottenuto usando la funzione numpy.linalg.det)             **[punti: 2]**
- sfruttarla per il calcolo della sua inversa risolvendo n sistemi lineari (confrontare l'inversa con quella ottenuta usando la funzione numpy.linalg.inv)
                                                                                                    **[punti: 2]**

In [159]:
A1 = np.array([[3.0, 2.0, 1.0, -1.0], [4.0, 6.0, 3.0, 2.0], [2.0, 1.0, 4.0, 3.0], [1.0, 4.0, 2.0, 7.0]])

P, L, U = sp.linalg.lu(A1)
n = A1.shape[0]

print("Calcolato det con la teoria:", np.linalg.det(P) * np.prod(np.diag(U)))
print("np.linalg.det:", np.linalg.det(A1))

Calcolato det con la teoria: 140.0
np.linalg.det: 140.00000000000006


In [183]:
I = np.identity(n)
x = np.zeros((n, n))
for i in range(n):
    y = np.linalg.solve(L, P@I[:, i])
    x[:, i] = np.linalg.solve(U, y)

print("Calcolato inv con la teoria:\n", x)
print("np.linalg.inv:\n", np.linalg.inv(A1))

Calcolato inv con la teoria:
 [[ 0.85       -0.45        0.          0.25      ]
 [-0.39285714  0.39285714 -0.14285714 -0.10714286]
 [-0.51428571  0.31428571  0.28571429 -0.28571429]
 [ 0.25       -0.25        0.          0.25      ]]
np.linalg.inv:
 [[ 0.85       -0.45        0.          0.25      ]
 [-0.39285714  0.39285714 -0.14285714 -0.10714286]
 [-0.51428571  0.31428571  0.28571429 -0.28571429]
 [ 0.25       -0.25        0.          0.25      ]]


## Esercizio 2

-  Implementare il  metodo di Newton Raphson, la variante delle corde e la variante di Shamanskii per la soluzione di un sistema non lineare
                           [**punti: 7**]

- Risolvere il sistema di equazioni non lineare 

$$
\left\{
\begin{array}{c}
x_0\cdot x_1+x_0=1 \\
 x_0^2+x_1^2=9
\end{array}
\right.
$$
con ciascuno dei tre metodi e confrontare per ciascun metodo il grafico dell'errore relativo tra due iterati successivi, giustificando i risultati alla luce della teoria. [**punti: 3**]

 **Nota Bene**: Servirsi del metodo grafico per individuare un 
iterato iniziale  $X^{(0)}$ nell'intorno della soluzione che si vuole approssimare.  Per fare cio',  visualizzare le 
curve di livello corrisponenti a z=0 delle due superfici $z_1 = f_1 (x_0 ,x_1 )$ e $z_2 = f_2(x_0 , x_1 )$ e 
definire come iterato iniziale un vettore $X^{(0)}=(x_0^{(0)},x_1^{(0)})$ oppurtuno le cui componenti appartengono ad un 
intorno della soluzione (cioè  dei punti di  intersezione tra le curve di livello delle due superfici) \]

- Descrivere teoricamente la variante del Metodo di Newton-Raphson per calcolare il minimo di una funzione non lineare in più variabili.

 [**punti: 2**]
 



In [196]:
def newton_raphson(initial_guess, F_numerical, J_Numerical, tolX, tolF, max_iterations):
    X= np.array(initial_guess, dtype=float)
    it=0
    erroreF=1+tolF
    erroreX=1+tolX
    errore=[]
    while it < max_iterations and erroreF >= tolF and erroreX >= tolX:
        jx = J_Numerical(X[0], X[1])
        if np.linalg.det(jx) == 0:
            print("La matrice dello Jacobiano calcolata nell'iterato precedente non è a rango massimo")
            return None, None,None
        fx = F_numerical(X[0], X[1])
        fx = fx.squeeze() 
        Xnew=X + s
        normaXnew=np.linalg.norm(Xnew)
        if normaXnew !=0:
            erroreX=np.linalg.norm(Xnew - X) / np.linalg.norm(X) 
        else:
            erroreX=np.linalg.norm(Xnew - X)
        errore.append(erroreX)
        fxnew=F_numerical(Xnew[0], Xnew[1])
        erroreF= np.linalg.norm(fxnew.squeeze())
        X=Xnew
        it=it+1
    return X,it,errore

In [198]:
def newton_raphson_corde(initial_guess, F_numerical, J_Numerical, tolX, tolF, max_iterations):
    X= np.array(initial_guess, dtype=float)
    it=0
    erroreF=1+tolF
    erroreX=1+tolX
    errore=[]
    while it < max_iterations and erroreF >= tolF and erroreX >= tolX:
        if it == 0:
            jx = J_Numerical(X[0], X[1])
            if np.linalg.det(jx) == 0:
                print("La matrice dello Jacobiano calcolata nell'iterato precedente non è a rango massimo")
                return None, None,None
        fx = F_numerical(X[0], X[1])
        fx = fx.squeeze() 
        s = np.linalg.solve(jx, -fx)
        Xnew=X + s
        normaXnew=np.linalg.norm(Xnew)
        if normaXnew !=0:
            erroreX=np.linalg.norm(Xnew - X) / np.linalg.norm(X) 
        else:
            erroreX=np.linalg.norm(Xnew - X)
        errore.append(erroreX)
        fxnew=F_numerical(Xnew[0], Xnew[1])
        erroreF= np.linalg.norm(fxnew.squeeze())
        X=Xnew
        it=it+1
    return X,it,errore

In [200]:
def newton_raphson_sham(initial_guess, update, F_numerical, J_Numerical, tolX, tolF, max_iterations):
    X= np.array(initial_guess, dtype=float)
    it=0
    erroreF=1+tolF
    erroreX=1+tolX
    errore=[]
    while it < max_iterations and erroreF >= tolF and erroreX >= tolX:
        if it % update:
            jx = J_Numerical(X[0], X[1])
            if np.linalg.det(jx) == 0:
                print("La matrice dello Jacobiano calcolata nell'iterato precedente non è a rango massimo")
                return None, None,None
        fx = F_numerical(X[0], X[1])
        fx = fx.squeeze() 
        s = np.linalg.solve(jx, -fx)
        Xnew=X + s
        normaXnew=np.linalg.norm(Xnew)
        if normaXnew !=0:
            erroreX=np.linalg.norm(Xnew - X) / np.linalg.norm(X) 
        else:
            erroreX=np.linalg.norm(Xnew - X)
        errore.append(erroreX)
        fxnew=F_numerical(Xnew[0], Xnew[1])
        erroreF= np.linalg.norm(fxnew.squeeze())
        X=Xnew
        it=it+1
    return X,it,errore

## Domande Intelligenza Artificiale
**NB: Ogni risposta esatta:  +0.5 punti, ogni risposta errata: -0.5 punti. La mancanza di risposta:  0 punti**

Domande a risposta multipla

**1.** Quali sono i passaggi fondamentali all’interno del paradigma generale dell’Intelligenza Artificiale?

•	Acquisizione dati, Data Processing, Addestramento del modello, Predizione e metriche

•	Data Processing, Addestramento del Modello, Predizione, Analisi economica dei risultati

•	Acquisizione dati, Data Processing, Addestramento del modello, Predizione, Test di Turing

•	Acquisizione dati, Addestramento del Modello, Test di Turing, Predizione


**2.** Per una rete neurale, l’apprendimento è legato a:

•	Minimizzare la funzione obiettivo

•	Minimizzare la funzione di attivazione

•	Massimizzare il valore dei pesi tramite l’algoritmo di back-propagation

•	Massimizzare il valore della funzione di training


**3.**  Il Test di Turing serve a:

•	Valutare se una macchina dimostra un comportamento intelligente

•	Valutare il carico computazionale di un algoritmo di Intelligenza Artificiale

•	Valutare la velocità di risposta di un algoritmo di Intelligenza Artificiale

•	Valutare se una macchina dimostra un comportamento predicibile


**4.**
Le ultime e più recenti innovazioni nel campo dell’Intelligenza Artificiale sono:

•	CNN, GAN e Transformers

•	Expert Systems, CNN e GAN

•	Expert Systems, Deep Learning e CNN

•	CNN, Expert Systems e Transformers


**5.** A cosa serve il validation set?

•	A trovare i migliori iperparametri del modello

•	Ad addestrare il modello 

•	A testare il modello

•	A trovare le etichette dei dati di input


**Domande aperte**

Quale è il ruolo del learning rate nella formula di aggiornamento dei pesi mediante gradient descent. Aggiornamento del learning rate programmato (learning rate scheduling) : step decay, decadimento esponenziale, decadimento dipendente dal tempo. **[punti 2]**


Learning rate adattivo per ogni peso (durante il processo di ottimizzazione) : Adagrad, RMSProp, Adadelta, Adam. (formula di aggiornamento dei pesi e discussioni)
**[punti 2.5]**